"""lead opportunity followup task

Revision ID: 013b6a76200a
Revises: 921b187030c3
Create Date: 2026-09-24 12:13:36.050013
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '013b6a76200a'
down_revision: Union[str, None] = '921b187030c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followups',
    sa.Column('customer_id', sa.BigInteger(), nullable=True),
    sa.Column('contact_id', sa.BigInteger(), nullable=True),
    sa.Column('lead_id', sa.BigInteger(), nullable=True),
    sa.Column('opportunity_id', sa.BigInteger(), nullable=True),
    sa.Column('quote_id', sa.BigInteger(), nullable=True),
    sa.Column('order_id', sa.BigInteger(), nullable=True),
    sa.Column('owner_id', sa.BigInteger(), nullable=True),
    sa.Column('followup_type', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('customer_feedback', sa.Text(), nullable=True),
    sa.Column('next_action', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_followups_customer_created', 'followups', ['customer_id', 'created_at'], unique=False)
    op.create_index('ix_followups_opportunity', 'followups', ['opportunity_id'], unique=False)
    op.create_table('lead_assignments',
    sa.Column('lead_id', sa.BigInteger(), nullable=False),
    sa.Column('from_user_id', sa.BigInteger(), nullable=True),
    sa.Column('to_user_id', sa.BigInteger(), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('operator_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leads',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=True),
    sa.Column('contact_name', sa.String(length=64), nullable=True),
    sa.Column('mobile', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.Column('source_detail', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('region', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('converted_customer_id', sa.BigInteger(), nullable=True),
    sa.Column('converted_contact_id', sa.BigInteger(), nullable=True),
    sa.Column('converted_opportunity_id', sa.BigInteger(), nullable=True),
    sa.Column('invalid_reason', sa.String(length=255), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('last_followup_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_leads_owner_status', 'leads', ['owner_id', 'status'], unique=False)
    op.create_table('loss_reasons',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('opportunity_stages',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('sequence', sa.BigInteger(), nullable=False),
    sa.Column('is_win', sa.Boolean(), nullable=False),
    sa.Column('is_loss', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('tasks',
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('task_type', sa.String(length=32), nullable=True),
    sa.Column('customer_id', sa.BigInteger(), nullable=True),
    sa.Column('contact_id', sa.BigInteger(), nullable=True),
    sa.Column('lead_id', sa.BigInteger(), nullable=True),
    sa.Column('opportunity_id', sa.BigInteger(), nullable=True),
    sa.Column('quote_id', sa.BigInteger(), nullable=True),
    sa.Column('order_id', sa.BigInteger(), nullable=True),
    sa.Column('owner_id', sa.BigInteger(), nullable=True),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('source_rule_id', sa.BigInteger(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completion_note', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tasks_owner_status_due', 'tasks', ['owner_id', 'status', 'due_at'], unique=False)
    op.create_table('opportunities',
    sa.Column('customer_id', sa.BigInteger(), nullable=False),
    sa.Column('primary_contact_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.Column('stage_id', sa.BigInteger(), nullable=False),
    sa.Column('expected_amount', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('expected_close_date', sa.Date(), nullable=True),
    sa.Column('owner_id', sa.BigInteger(), nullable=True),
    sa.Column('competitor', sa.String(length=128), nullable=True),
    sa.Column('risk_level', sa.String(length=16), nullable=True),
    sa.Column('next_action', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('win_quote_version_id', sa.BigInteger(), nullable=True),
    sa.Column('loss_reason_id', sa.BigInteger(), nullable=True),
    sa.Column('loss_remark', sa.Text(), nullable=True),
    sa.Column('reopen_at', sa.Date(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['opportunity_stages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_opportunities_customer_status', 'opportunities', ['customer_id', 'status'], unique=False)
    op.create_index('ix_opportunities_owner_stage', 'opportunities', ['owner_id', 'stage_id'], unique=False)
    op.create_table('opportunity_items',
    sa.Column('opportunity_id', sa.BigInteger(), nullable=False),
    sa.Column('sku_id', sa.BigInteger(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=16, scale=3), nullable=False),
    sa.Column('target_price', sa.Numeric(precision=16, scale=4), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('specification', sa.String(length=200), nullable=True),
    sa.Column('color', sa.String(length=64), nullable=True),
    sa.Column('package_requirement', sa.String(length=128), nullable=True),
    sa.Column('delivery_date', sa.Date(), nullable=True),
    sa.Column('destination', sa.String(length=128), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_opportunity_items_opportunity', 'opportunity_items', ['opportunity_id'], unique=False)
    op.create_table('opportunity_stage_history',
    sa.Column('opportunity_id', sa.BigInteger(), nullable=False),
    sa.Column('from_stage_id', sa.BigInteger(), nullable=True),
    sa.Column('to_stage_id', sa.BigInteger(), nullable=False),
    sa.Column('operator_id', sa.BigInteger(), nullable=True),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('entered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_stage_history_opportunity', 'opportunity_stage_history', ['opportunity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_stage_history_opportunity', table_name='opportunity_stage_history')
    op.drop_table('opportunity_stage_history')
    op.drop_index('ix_opportunity_items_opportunity', table_name='opportunity_items')
    op.drop_table('opportunity_items')
    op.drop_index('ix_opportunities_owner_stage', table_name='opportunities')
    op.drop_index('ix_opportunities_customer_status', table_name='opportunities')
    op.drop_table('opportunities')
    op.drop_index('ix_tasks_owner_status_due', table_name='tasks')
    op.drop_table('tasks')
    op.drop_table('opportunity_stages')
    op.drop_table('loss_reasons')
    op.drop_index('ix_leads_owner_status', table_name='leads')
    op.drop_table('leads')
    op.drop_table('lead_assignments')
    op.drop_index('ix_followups_opportunity', table_name='followups')
    op.drop_index('ix_followups_customer_created', table_name='followups')
    op.drop_table('followups')
    # ### end Alembic commands ###
