"""order receivable payment integration

Revision ID: 25e2fd95da23
Revises: ec20812a556d
Create Date: 2026-09-24 13:28:08.001020
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '25e2fd95da23'
down_revision: Union[str, None] = 'ec20812a556d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_mappings',
    sa.Column('system_type', sa.String(length=32), nullable=False),
    sa.Column('business_type', sa.String(length=32), nullable=False),
    sa.Column('internal_id', sa.BigInteger(), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=True),
    sa.Column('external_code', sa.String(length=128), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_external_mappings_external', 'external_mappings', ['system_type', 'external_id'], unique=False)
    op.create_index('ix_external_mappings_lookup', 'external_mappings', ['system_type', 'business_type', 'internal_id'], unique=False)
    op.create_table('integration_logs',
    sa.Column('integration_type', sa.String(length=32), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('business_type', sa.String(length=32), nullable=True),
    sa.Column('business_id', sa.BigInteger(), nullable=True),
    sa.Column('request_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('response_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sales_orders',
    sa.Column('order_no', sa.String(length=32), nullable=False),
    sa.Column('customer_id', sa.BigInteger(), nullable=False),
    sa.Column('opportunity_id', sa.BigInteger(), nullable=True),
    sa.Column('quote_id', sa.BigInteger(), nullable=True),
    sa.Column('quote_version_id', sa.BigInteger(), nullable=True),
    sa.Column('owner_id', sa.BigInteger(), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('erp_order_id', sa.String(length=64), nullable=True),
    sa.Column('delivery_date', sa.Date(), nullable=True),
    sa.Column('payment_terms', sa.String(length=128), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_no')
    )
    op.create_index('ix_sales_orders_customer', 'sales_orders', ['customer_id'], unique=False)
    op.create_index('ix_sales_orders_quote_version', 'sales_orders', ['quote_version_id'], unique=True)
    op.create_table('order_status_history',
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('old_status', sa.String(length=24), nullable=True),
    sa.Column('new_status', sa.String(length=24), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('operator_id', sa.BigInteger(), nullable=True),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['sales_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_order_status_history_order', 'order_status_history', ['order_id'], unique=False)
    op.create_table('payment_records',
    sa.Column('receivable_plan_id', sa.BigInteger(), nullable=True),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('received_date', sa.Date(), nullable=False),
    sa.Column('received_amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('payment_method', sa.String(length=32), nullable=True),
    sa.Column('voucher_file_id', sa.BigInteger(), nullable=True),
    sa.Column('voucher_note', sa.String(length=255), nullable=True),
    sa.Column('confirmed_by', sa.BigInteger(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['sales_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_payment_records_order', 'payment_records', ['order_id'], unique=False)
    op.create_index('ix_payment_records_plan', 'payment_records', ['receivable_plan_id'], unique=False)
    op.create_table('receivable_plans',
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('plan_name', sa.String(length=64), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['sales_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_receivable_plans_order_status', 'receivable_plans', ['order_id', 'status'], unique=False)
    op.create_table('sales_order_items',
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('sku_id', sa.BigInteger(), nullable=False),
    sa.Column('sku_snapshot', sa.String(length=200), nullable=True),
    sa.Column('specification', sa.String(length=200), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=16, scale=3), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=16, scale=4), nullable=False),
    sa.Column('amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['sales_orders.id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sales_order_items_order', 'sales_order_items', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sales_order_items_order', table_name='sales_order_items')
    op.drop_table('sales_order_items')
    op.drop_index('ix_receivable_plans_order_status', table_name='receivable_plans')
    op.drop_table('receivable_plans')
    op.drop_index('ix_payment_records_plan', table_name='payment_records')
    op.drop_index('ix_payment_records_order', table_name='payment_records')
    op.drop_table('payment_records')
    op.drop_index('ix_order_status_history_order', table_name='order_status_history')
    op.drop_table('order_status_history')
    op.drop_index('ix_sales_orders_quote_version', table_name='sales_orders')
    op.drop_index('ix_sales_orders_customer', table_name='sales_orders')
    op.drop_table('sales_orders')
    op.drop_table('integration_logs')
    op.drop_index('ix_external_mappings_lookup', table_name='external_mappings')
    op.drop_index('ix_external_mappings_external', table_name='external_mappings')
    op.drop_table('external_mappings')
    # ### end Alembic commands ###
