"""product and sku

Revision ID: 921b187030c3
Revises: aaab3b453150
Create Date: 2026-09-24 12:00:25.463398
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '921b187030c3'
down_revision: Union[str, None] = 'aaab3b453150'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('product_line', sa.String(length=64), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('brand', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('knowledge', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_products_name', 'products', ['name'], unique=False)
    op.create_table('skus',
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('sku_code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('specification', sa.String(length=200), nullable=True),
    sa.Column('color', sa.String(length=64), nullable=True),
    sa.Column('material', sa.String(length=64), nullable=True),
    sa.Column('length', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('width', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('height', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('weight', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('carton_qty', sa.BigInteger(), nullable=True),
    sa.Column('carton_volume', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('moq', sa.BigInteger(), nullable=True),
    sa.Column('package_type', sa.String(length=64), nullable=True),
    sa.Column('unit', sa.String(length=16), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_skus_code', 'skus', ['sku_code'], unique=True)
    op.create_index('ix_skus_product', 'skus', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_skus_product', table_name='skus')
    op.drop_index('ix_skus_code', table_name='skus')
    op.drop_table('skus')
    op.drop_index('ix_products_name', table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
