"""exchange rate and export fields

Revision ID: a4034e4ebed1
Revises: b740afe4d078
Create Date: 2026-09-24 17:30:11.364854
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a4034e4ebed1'
down_revision: Union[str, None] = 'b740afe4d078'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange_rates',
    sa.Column('base_currency', sa.String(length=8), nullable=False),
    sa.Column('quote_currency', sa.String(length=8), nullable=False),
    sa.Column('rate', sa.Numeric(precision=16, scale=6), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_exchange_rates_pair', 'exchange_rates', ['base_currency', 'quote_currency'], unique=False)
    op.add_column('quote_items', sa.Column('tax_refund_snapshot', sa.Numeric(precision=16, scale=4), server_default='0', nullable=False))
    op.add_column('quote_items', sa.Column('profit_with_refund_snapshot', sa.Numeric(precision=16, scale=4), server_default='0', nullable=False))
    op.add_column('quote_versions', sa.Column('exchange_rate_snapshot', sa.Numeric(precision=16, scale=6), nullable=True))
    op.add_column('quote_versions', sa.Column('exchange_rate_source', sa.String(length=64), nullable=True))
    op.add_column('quote_versions', sa.Column('exchange_rate_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('quote_versions', sa.Column('trade_terms', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quote_versions', 'trade_terms')
    op.drop_column('quote_versions', 'exchange_rate_time')
    op.drop_column('quote_versions', 'exchange_rate_source')
    op.drop_column('quote_versions', 'exchange_rate_snapshot')
    op.drop_column('quote_items', 'profit_with_refund_snapshot')
    op.drop_column('quote_items', 'tax_refund_snapshot')
    op.drop_index('ix_exchange_rates_pair', table_name='exchange_rates')
    op.drop_table('exchange_rates')
    # ### end Alembic commands ###
