"""agent

Revision ID: b740afe4d078
Revises: ac56888d214f
Create Date: 2026-09-24 14:13:20.025372
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'b740afe4d078'
down_revision: Union[str, None] = 'ac56888d214f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_actions',
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('action_type', sa.String(length=64), nullable=False),
    sa.Column('tool_name', sa.String(length=64), nullable=False),
    sa.Column('risk_level', sa.String(length=4), nullable=False),
    sa.Column('business_type', sa.String(length=32), nullable=True),
    sa.Column('business_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('proposed_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('result', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('confirmed_by', sa.BigInteger(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_actions_session', 'agent_actions', ['session_id'], unique=False)
    op.create_table('agent_executions',
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('action_id', sa.BigInteger(), nullable=True),
    sa.Column('tool_name', sa.String(length=64), nullable=False),
    sa.Column('risk_level', sa.String(length=4), nullable=False),
    sa.Column('input_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('output_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_executions_session', 'agent_executions', ['session_id'], unique=False)
    op.create_table('agent_messages',
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('tool_name', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_messages_session', 'agent_messages', ['session_id'], unique=False)
    op.create_table('agent_sessions',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('context_type', sa.String(length=32), nullable=True),
    sa.Column('context_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_sessions_user', 'agent_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_agent_sessions_user', table_name='agent_sessions')
    op.drop_table('agent_sessions')
    op.drop_index('ix_agent_messages_session', table_name='agent_messages')
    op.drop_table('agent_messages')
    op.drop_index('ix_agent_executions_session', table_name='agent_executions')
    op.drop_table('agent_executions')
    op.drop_index('ix_agent_actions_session', table_name='agent_actions')
    op.drop_table('agent_actions')
    # ### end Alembic commands ###
