"""pricing: cost price rule permission logistics

Revision ID: cc71067e3f6c
Revises: 013b6a76200a
Create Date: 2026-09-24 12:47:28.744849
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'cc71067e3f6c'
down_revision: Union[str, None] = '013b6a76200a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logistics_rates',
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('destination_region', sa.String(length=64), nullable=True),
    sa.Column('shipping_method', sa.String(length=32), nullable=False),
    sa.Column('unit_price_per_kg', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('min_charge', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('eta_days', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('price_permissions',
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('minimum_margin', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('discount_limit', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('can_approve', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_price_permissions_role', 'price_permissions', ['role_id'], unique=False)
    op.create_table('price_rules',
    sa.Column('sku_id', sa.BigInteger(), nullable=False),
    sa.Column('customer_level', sa.String(length=8), nullable=True),
    sa.Column('min_qty', sa.Numeric(precision=16, scale=3), nullable=False),
    sa.Column('max_qty', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('standard_price', sa.Numeric(precision=16, scale=4), nullable=True),
    sa.Column('guide_price', sa.Numeric(precision=16, scale=4), nullable=True),
    sa.Column('minimum_price', sa.Numeric(precision=16, scale=4), nullable=True),
    sa.Column('target_margin', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_price_rules_sku', 'price_rules', ['sku_id', 'status'], unique=False)
    op.create_table('product_costs',
    sa.Column('sku_id', sa.BigInteger(), nullable=False),
    sa.Column('purchase_cost', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('production_cost', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('package_cost', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('processing_cost', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_product_costs_sku', 'product_costs', ['sku_id', 'effective_from'], unique=False)
    op.create_table('customer_price_rules',
    sa.Column('customer_id', sa.BigInteger(), nullable=False),
    sa.Column('sku_id', sa.BigInteger(), nullable=False),
    sa.Column('min_qty', sa.Numeric(precision=16, scale=3), nullable=False),
    sa.Column('max_qty', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('agreed_price', sa.Numeric(precision=16, scale=4), nullable=False),
    sa.Column('minimum_price', sa.Numeric(precision=16, scale=4), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_customer_price_rules_customer', 'customer_price_rules', ['customer_id', 'sku_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_customer_price_rules_customer', table_name='customer_price_rules')
    op.drop_table('customer_price_rules')
    op.drop_index('ix_product_costs_sku', table_name='product_costs')
    op.drop_table('product_costs')
    op.drop_index('ix_price_rules_sku', table_name='price_rules')
    op.drop_table('price_rules')
    op.drop_index('ix_price_permissions_role', table_name='price_permissions')
    op.drop_table('price_permissions')
    op.drop_table('logistics_rates')
    # ### end Alembic commands ###
