"""quote approval pdf

Revision ID: ec20812a556d
Revises: cc71067e3f6c
Create Date: 2026-09-24 13:09:05.189450
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'ec20812a556d'
down_revision: Union[str, None] = 'cc71067e3f6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_definitions',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('business_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('config_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('approval_instances',
    sa.Column('definition_id', sa.BigInteger(), nullable=False),
    sa.Column('business_type', sa.String(length=64), nullable=False),
    sa.Column('business_id', sa.BigInteger(), nullable=False),
    sa.Column('applicant_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('current_node', sa.String(length=32), nullable=True),
    sa.Column('summary', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['definition_id'], ['approval_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_approval_instances_business', 'approval_instances', ['business_type', 'business_id'], unique=False)
    op.create_table('approval_records',
    sa.Column('approval_instance_id', sa.BigInteger(), nullable=False),
    sa.Column('node_code', sa.String(length=32), nullable=True),
    sa.Column('approver_id', sa.BigInteger(), nullable=True),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['approval_instance_id'], ['approval_instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_approval_records_instance', 'approval_records', ['approval_instance_id'], unique=False)
    op.create_table('quotes',
    sa.Column('quote_no', sa.String(length=32), nullable=False),
    sa.Column('opportunity_id', sa.BigInteger(), nullable=True),
    sa.Column('customer_id', sa.BigInteger(), nullable=False),
    sa.Column('contact_id', sa.BigInteger(), nullable=True),
    sa.Column('owner_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('current_version_id', sa.BigInteger(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quote_no')
    )
    op.create_index('ix_quotes_customer', 'quotes', ['customer_id'], unique=False)
    op.create_index('ix_quotes_opportunity', 'quotes', ['opportunity_id'], unique=False)
    op.create_table('quote_versions',
    sa.Column('quote_id', sa.BigInteger(), nullable=False),
    sa.Column('version_no', sa.BigInteger(), nullable=False),
    sa.Column('subtotal_amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('charge_amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('payment_terms', sa.String(length=128), nullable=True),
    sa.Column('delivery_terms', sa.String(length=128), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('approval_status', sa.String(length=24), nullable=False),
    sa.Column('approval_required', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('declined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_quote_versions_quote', 'quote_versions', ['quote_id'], unique=False)
    op.create_table('quote_charges',
    sa.Column('quote_version_id', sa.BigInteger(), nullable=False),
    sa.Column('charge_type', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('is_discount', sa.Boolean(), nullable=False),
    sa.Column('sort_no', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['quote_version_id'], ['quote_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quote_items',
    sa.Column('quote_version_id', sa.BigInteger(), nullable=False),
    sa.Column('opportunity_item_id', sa.BigInteger(), nullable=True),
    sa.Column('sku_id', sa.BigInteger(), nullable=False),
    sa.Column('sku_code_snapshot', sa.String(length=64), nullable=True),
    sa.Column('sku_name_snapshot', sa.String(length=200), nullable=True),
    sa.Column('spec_snapshot', sa.String(length=200), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=16, scale=3), nullable=False),
    sa.Column('cost_snapshot', sa.Numeric(precision=16, scale=4), nullable=False),
    sa.Column('package_cost_snapshot', sa.Numeric(precision=16, scale=4), nullable=False),
    sa.Column('logistics_cost_snapshot', sa.Numeric(precision=16, scale=4), nullable=False),
    sa.Column('standard_price_snapshot', sa.Numeric(precision=16, scale=4), nullable=True),
    sa.Column('recommended_price_snapshot', sa.Numeric(precision=16, scale=4), nullable=True),
    sa.Column('minimum_price_snapshot', sa.Numeric(precision=16, scale=4), nullable=True),
    sa.Column('quoted_price', sa.Numeric(precision=16, scale=4), nullable=False),
    sa.Column('profit_snapshot', sa.Numeric(precision=16, scale=4), nullable=False),
    sa.Column('profit_rate_snapshot', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('approval_required', sa.Boolean(), nullable=False),
    sa.Column('approval_reason', sa.String(length=255), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['quote_version_id'], ['quote_versions.id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_quote_items_version', 'quote_items', ['quote_version_id'], unique=False)
    op.create_table('quote_send_logs',
    sa.Column('quote_version_id', sa.BigInteger(), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('receiver', sa.String(length=128), nullable=True),
    sa.Column('sent_by', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('error_message', sa.String(length=255), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['quote_version_id'], ['quote_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quote_send_logs')
    op.drop_index('ix_quote_items_version', table_name='quote_items')
    op.drop_table('quote_items')
    op.drop_table('quote_charges')
    op.drop_index('ix_quote_versions_quote', table_name='quote_versions')
    op.drop_table('quote_versions')
    op.drop_index('ix_quotes_opportunity', table_name='quotes')
    op.drop_index('ix_quotes_customer', table_name='quotes')
    op.drop_table('quotes')
    op.drop_index('ix_approval_records_instance', table_name='approval_records')
    op.drop_table('approval_records')
    op.drop_index('ix_approval_instances_business', table_name='approval_instances')
    op.drop_table('approval_instances')
    op.drop_table('approval_definitions')
    # ### end Alembic commands ###
